namespace Ryujinx.HLE.HOS.Services.Ssl.Types
{
    enum CaCertificateId : uint
    {
        // Nintendo CAs
        NintendoCAG3 = 1,
        NintendoClass2CAG3,

        // External CAs
        AmazonRootCA1 = 1000,
        StarfieldServicesRootCertificateAuthorityG2,
        AddTrustExternalCARoot,
        COMODOCertificationAuthority,
        UTNDATACorpSGC,
        UTNUSERFirstHardware,
        BaltimoreCyberTrustRoot,
        CybertrustGlobalRoot,
        VerizonGlobalRootCA,
        DigiCertAssuredIDRootCA,
        DigiCertAssuredIDRootG2,
        DigiCertGlobalRootCA,
        DigiCertGlobalRootG2,
        DigiCertHighAssuranceEVRootCA,
        EntrustnetCertificationAuthority2048,
        EntrustRootCertificationAuthority,
        EntrustRootCertificationAuthorityG2,
        GeoTrustGlobalCA2,
        GeoTrustGlobalCA,
        GeoTrustPrimaryCertificationAuthorityG3,
        GeoTrustPrimaryCertificationAuthority,
        GlobalSignRootCA,
        GlobalSignRootCAR2,
        GlobalSignRootCAR3,
        GoDaddyClass2CertificationAuthority,
        GoDaddyRootCertificateAuthorityG2,
        StarfieldClass2CertificationAuthority,
        StarfieldRootCertificateAuthorityG2,
        ThawtePrimaryRootCAG3,
        ThawtePrimaryRootCA,
        VeriSignClass3PublicPrimaryCertificationAuthorityG3,
        VeriSignClass3PublicPrimaryCertificationAuthorityG5,
        VeriSignUniversalRootCertificationAuthority,
        DSTRootCAX3,
        USERTrustRSACertificationAuthority,
        ISRGRootX10,
        USERTrustECCCertificationAuthority,
        COMODORSACertificationAuthority,
        COMODOECCCertificationAuthority,
        AmazonRootCA2,
        AmazonRootCA3,
        AmazonRootCA4,
        DigiCertAssuredIDRootG3,
        DigiCertGlobalRootG3,
        DigiCertTrustedRootG4,
        EntrustRootCertificationAuthorityEC1,
        EntrustRootCertificationAuthorityG4,
        GlobalSignECCRootCAR4,
        GlobalSignECCRootCAR5,
        GlobalSignECCRootCAR6,
        GTSRootR1,
        GTSRootR2,
        GTSRootR3,
        GTSRootR4,
        SecurityCommunicationRootCA,

        All = uint.MaxValue,
    }
}
