namespace Ryujinx.HLE.HOS.Services.Spl.Types
{
    enum DramId
    {
        IcosaSamsung4GB,
        IcosaHynix4GB,
        IcosaMicron4GB,
        IowaHynix1y4GB,
        IcosaSamsung6GB,
        HoagHynix1y4GB,
        AulaHynix1y4GB,
        IowaX1X2Samsung4GB,
        IowaSansung4GB,
        IowaSamsung8GB,
        IowaHynix4GB,
        IowaMicron4GB,
        HoagSamsung4GB,
        HoagSamsung8GB,
        HoagHynix4GB,
        HoagMicron4GB,
        IowaSamsung4GBY,
        IowaSamsung1y4GBX,
        IowaSamsung1y8GBX,
        HoagSamsung1y4GBX,
        IowaSamsung1y4GBY,
        IowaSamsung1y8GBY,
        AulaSamsung1y4GB,
        HoagSamsung1y8GBX,
        AulaSamsung1y4GBX,
        IowaMicron1y4GB,
        HoagMicron1y4GB,
        AulaMicron1y4GB,
        AulaSamsung1y8GBX
    }
}