namespace Ryujinx.Core.Logging
{
    public enum LogClass
    {
        Audio,
        Cpu,
        Gpu,
        Hid,
        Kernel,
        KernelIpc,
        KernelScheduler,
        KernelSvc,
        Loader,
        Service,
        ServiceAcc,
        ServiceAm,
        ServiceApm,
        ServiceAudio,
        ServiceBsd,
        ServiceCaps,
        ServiceFriend,
        ServiceFs,
        ServiceHid,
        ServiceLm,
        ServiceMm,
        ServiceNifm,
        ServiceNs,
        ServiceNv,
        ServicePctl,
        ServicePl,
        ServicePrepo,
        ServiceSet,
        ServiceSfdnsres,
        ServiceSm,
        ServiceSss,
        ServiceTime,
        ServiceVi
    }
}
