namespace Ryujinx.Core.OsHle.IpcServices
{
    enum ErrorModule
    {
        Kernel                = 1,
        Fs                    = 2,
        Nvidia_TransferMemory = 3,
        Ncm                   = 5,
        Dd                    = 6,
        Lr                    = 8,
        Loader                = 9,
        IPC_Command_Interface = 10,
        IPC                   = 11,
        Pm                    = 15,
        Ns                    = 16,
        Htc                   = 18,
        Sm                    = 21,
        RO_Userland           = 22,
        SdMmc                 = 24,
        Spl                   = 26,
        Ethc                  = 100,
        I2C                   = 101,
        Settings              = 105,
        Nifm                  = 110,
        Display               = 114,
        Ntc                   = 116,
        Fdm                   = 117,
        Pcie                  = 120,
        Friends               = 121,
        SSL                   = 123,
        Account               = 124,
        Mii                   = 126,
        Am                    = 128,
        Play_Report           = 129,
        Pcv                   = 133,
        Omm                   = 134,
        Nim                   = 137,
        Psc                   = 138,
        Usb                   = 140,
        Nsd                   = 141,
        Btm                   = 143,
        Erpt                  = 147,
        Apm                   = 148,
        Audio                 = 153,
        Npns                  = 154,
        Arp                   = 157,
        Boot                  = 158,
        Nfc                   = 161,
        Userland_Assert       = 162,
        Userland_Crash        = 168,
        Hid                   = 203,
        Capture               = 206,
        Libnx                 = 345,
        Homebrew_ABI          = 346,
        Homebrew_Loader       = 347,
        libnx_Nvidia_Errors   = 348,
        Tc                    = 651,
        General_Web_Applet    = 800,
        Wifi_Web_Auth_Applet  = 809,
        Whitelisted_Applet    = 810,
        ShopN                 = 811
    }
}